-- Removes what seed.sql inserted, and only that.
--
-- Matched on the description rather than on the owner: a load run against a
-- shared environment must not delete rows a human created under the same user.
DELETE FROM demo_item
WHERE description = 'generated by load-test/scripts/seed.sql';

-- Rows the simulation itself created and failed to clean up (a KO between POST
-- and DELETE leaves one behind).
DELETE FROM demo_item
WHERE name LIKE 'load-%';

ANALYZE demo_item;
