-- Seed data for a read-heavy load run.
--
-- Inserted directly rather than through the API: creating 5000 items over HTTP
-- takes minutes and measures the write path, which is not what the read
-- scenarios are for.
--
-- Owner id has to match the subject of the token the simulation uses, or every
-- request will correctly return an empty list and the run will measure nothing.
-- Override with:  psql -v owner="'some-user'" -f seed.sql
\set owner :owner

INSERT INTO demo_item (id, name, description, status, owner_id, created_at, version)
SELECT gen_random_uuid(),
       'seeded item ' || i,
       'generated by load-test/scripts/seed.sql',
       CASE WHEN i % 3 = 0 THEN 'ACTIVE' ELSE 'DRAFT' END,
       :owner,
       now() - (i || ' minutes')::interval,
       0
FROM generate_series(1, 5000) AS s(i);

ANALYZE demo_item;
